import {
  faPerson,
  faCaretDown,
  faSkullCrossbones,
  faBurst,
  faFlask,
  faTableList,
  faExclamation,
  faPeopleGroup,
  faCoins,
  faMountain,
  faScrewdriverWrench,
  faUser,
  faToolbox,
  faBook,
  faDungeon,
  faDoorOpen,
  faDoorClosed,
  faLocationPin,
  faLocationDot,
  faMap,
  faQuestion,
  faHouseChimney,
  faGem
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  person: faPerson,
  caretDown: faCaretDown,
  skullCrossbones: faSkullCrossbones,
  burst:faBurst,
  flask: faFlask,
  table: faTableList,
  exclamation: faExclamation,
  peopleGroup: faPeopleGroup,
  coins: faCoins,
  mountain: faMountain,
  screwdriverWrench: faScrewdriverWrench,
  user: faUser,
  toolbox: faToolbox,
  book: faBook,
  dungeon: faDungeon,
  doorOpen: faDoorOpen,
  doorClosed: faDoorClosed,
  locationPin: faLocationPin,
  locationDot: faLocationDot,
  map: faMap,
  question: faQuestion,
  houseChimney: faHouseChimney,
  gem: faGem,
};