import {
  faPerson,
  faCaretDown,
  faSkullCrossbones,
  faBurst,
  faFlask,
  faTableList,
  faExclamation,
  faPeopleGroup,
  faCoins,
  faMountain,
  faScrewdriverWrench,
  faUser,
  faToolbox,
  faBook,
  faDungeon,
  faDoorOpen,
  faDoorClosed,
  faLocationPin,
  faLocationDot,
  faMap,
  faQuestion,
  faHouseChimney,
  faGem,
  faStar,
  faPlus,
  faRotateLeft,
  faRotateRight,
  faBars,
  faCircleQuestion,
  faCirclePlus,
  faCircleMinus,
  faTrash,
} from '@fortawesome/free-solid-svg-icons';

import { 
  faStar as faRegStar,
} from '@fortawesome/free-regular-svg-icons';

export const icons = {
  book: faBook,
  burst:faBurst,
  caretDown: faCaretDown,
  coins: faCoins,
  doorClosed: faDoorClosed,
  doorOpen: faDoorOpen,
  dungeon: faDungeon,
  exclamation: faExclamation,
  flask: faFlask,
  gem: faGem,
  houseChimney: faHouseChimney,
  locationDot: faLocationDot,
  locationPin: faLocationPin,
  map: faMap,
  mountain: faMountain,
  peopleGroup: faPeopleGroup,
  person: faPerson,
  question: faQuestion,
  regStar: faRegStar,
  screwdriverWrench: faScrewdriverWrench,
  skullCrossbones: faSkullCrossbones,
  star: faStar,
  table: faTableList,
  toolbox: faToolbox,
  user: faUser,
  plus: faPlus,
  rotateLeft: faRotateLeft,
  rotateRight: faRotateRight,
  bars: faBars,
  circleQuestion: faCircleQuestion,
  circlePlus: faCirclePlus,
  circleMinus: faCircleMinus,
  trash: faTrash,
};